force-app/main/default/objects/Confluence_Event__c/Confluence_Event__c.object-meta.xml
<CustomObject>
    <label>Confluence Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Confluent Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Confluence Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Confluence_Event__c/fields/Page_Content__c.field-meta.xml
<CustomField>
    <fullName>Page_Content__c</fullName>
    <label>Page Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ConfluenceCallout.cls
public class ConfluenceCallout implements Queueable, Database.AllowsCallouts {
    private Id recordId;
    private String pageId;

    public ConfluenceCallout(Id recordId, String pageId) {
        this.recordId = recordId;
        this.pageId = pageId;
    }

    public void execute(QueueableContext context) {
        String html = ConfluenceAPI.getPageHTML(pageId); 

        if (html != null) {
            Confluence_Event__c updateRec = new Confluence_Event__c(Id = recordId);
            updateRec.Page_Content__c = html;
            update updateRec;
        }
    }

    public static void fetchHTMLAsync(Id recordId, String pageId) {
        System.enqueueJob(new ConfluenceCallout(recordId, pageId));
    }
}